{"name": "# Verify that cart has \"1\" item", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\012_cart_has_one_item.py\", line 8, in cart_has_ine_item\n    context.app.main_page.cart_has_ine_item(qntty)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 383, in cart_has_ine_item\n    target = wait.until(EC.element_to_be_clickable(CLOSE_SHOPPING_CART))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1623807972600, "stop": 1623807973430}, {"name": "Then Verify that cart has 1 item", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\012_cart_has_one_item.py\", line 8, in cart_has_ine_item\n    context.app.main_page.cart_has_ine_item(qntty)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 383, in cart_has_ine_item\n    target = wait.until(EC.element_to_be_clickable(CLOSE_SHOPPING_CART))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1623807973430, "stop": 1623807989578}], "start": 1623807968010, "stop": 1623807991891, "uuid": "345941b1-8e43-4db6-9c2d-bbbab34f3634", "historyId": "5f1f82d3794fe184eb4e60a9f615f056", "fullName": "# Verify that cart has \"1\" item: # Verify that cart has \"1\" item", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# Verify that cart has \"1\" item"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}